Part 1
RemZiQ/js-assignments pull request #1
Opened 2019-02-18 08:54 UTC by RemZiQ

Added solutions for strings, numbers, date and some arrays tasks.

2019-02-20 12:22 UTC, RamanRudski requested changes

2019-02-20 12:22 UTC, RamanRudski commented on task/01-strings-tasks.js
> +  return String.fromCharCode(9484) + String.fromCharCode(9472).repeat(width - 2) + String.fromCharCode(9488) + '\n' +(String.fromCharCode(9474) + ' '.repeat(width - 2) + String.fromCharCode(9474) + '
`String.fromCharCode(9484)` все эти штуки нужно вынести в переменные. 
Длинна строки не должна превышать 120 символов, нереально читать код.

2019-02-20 12:22 UTC, RamanRudski commented on task/01-strings-tasks.js
> +    return String.fromCharCode((c<='Z'?90:122)>=(c=c.charCodeAt(0)+13)?c:c-26);
`? = + /` и т.д. отделяется пробелами с двух сторон. Стиль кода должен быть везде одинаковым.

2019-02-20 12:22 UTC, RamanRudski commented on task/02-numbers-tasks.js
> +  return Math.sqrt(Math.pow(x2 - x1, 2) + Math.pow(y2 - y1, 2));
Решение может быть короче при использовании `Math.hypot`

2019-02-20 12:22 UTC, RamanRudski commented on task/02-numbers-tasks.js
> +  return Math.acos((x1 * x2 + y1 * y2) / (Math.sqrt(Math.pow(x1, 2) + Math.pow(y1, 2)) * Math.sqrt(Math.pow(x2, 2) + Math.pow(y2, 2)))); // eslint-disable-line
`Math.sqrt(Math.pow(x1, 2) + Math.pow(y1, 2))` смотри комментарий выше

2019-02-20 12:22 UTC, RamanRudski commented on task/02-numbers-tasks.js
> +  return +value.toString().split('').pop();
`pop()` нужен не для этого. В первую очередь он удаляет последний элемент массива, используй другое решение.

2019-02-20 12:22 UTC, RamanRudski commented on task/02-numbers-tasks.js
> +  return Math.sqrt(a * a + b * b + c * c);
Лучше использовать `Math.hypot()`

2019-02-20 12:22 UTC, RamanRudski commented on task/03-date-tasks.js
> +  return (date.getFullYear() % 4 === 0) && (date.getFullYear() % 100 !== 0) || (date.getFullYear() % 400 === 0); // eslint-disable-line
Вынеси в переменную `date.getFullYear()`, не нужно выполнять одну и туже операцию 3 раза.

2019-02-20 12:22 UTC, RamanRudski commented on task/03-date-tasks.js
> +  let hours = +date.toISOString().substring(11, 13);
Это плохое решение, используй `getUTCHours()`

2019-02-20 12:22 UTC, RamanRudski commented on task/04-arrays-tasks.js
> +  return arr.filter(elem => !!elem);
`!!elem` не нужно, достаточно просто `elem`

2019-02-20 12:22 UTC, RamanRudski commented on task/04-arrays-tasks.js
>  function getMovingSum(arr) {
Эта задача подразумевает использование `reduce`, переделай с его использованием.

2019-02-20 12:22 UTC, RamanRudski commented on task/04-arrays-tasks.js
>  function propagateItemsByPositionIndex(arr) {
Используй тут `reduce`

2019-02-20 12:22 UTC, RamanRudski commented on task/04-arrays-tasks.js
> +  return arr.map(item => m.indexOf(item)).sort((a, b) => a - b).map(item => m[item]);  //eslint-disable-line
можно сделать проще, задействовав только `sort`.В твоем решение много лишних проходов по массиву, плохо для производительности.

2019-02-20 12:22 UTC, RamanRudski commented on task/04-arrays-tasks.js
> -  throw new Error('Not implemented');
Плохо. Используй `reduce`.

2019-02-20 12:22 UTC, RamanRudski commented on task/04-arrays-tasks.js
> +  return new Array(n).fill(0).map((item, indexMainArray) => {
необязательный `map`, ты можешь использовать `fill()` для заполнения не нулями а сражу массивами. Так ты избежишь лишнего прохода массива.

2019-02-20 16:47 UTC, RemZiQ commented on task/01-strings-tasks.js
> +  return String.fromCharCode(9484) + String.fromCharCode(9472).repeat(width - 2) + String.fromCharCode(9488) + '\n' +(String.fromCharCode(9474) + ' '.repeat(width - 2) + String.fromCharCode(9474) + '
Сделал const f = String.fromCharcode чтобы сократить код. Читабельность кода страдает. Лучшее что смог придумать при длинне строки 80 символов и максимум 4 строки кода. Переменные для каждого отдельного символа не поместятся в 4 строки.

2019-02-20 16:47 UTC, RemZiQ commented on task/01-strings-tasks.js
> +    return String.fromCharCode((c<='Z'?90:122)>=(c=c.charCodeAt(0)+13)?c:c-26);
Пофиксил

2019-02-20 16:47 UTC, RemZiQ commented on task/02-numbers-tasks.js
> +  return Math.sqrt(Math.pow(x2 - x1, 2) + Math.pow(y2 - y1, 2));
Пофиксил

2019-02-20 16:47 UTC, RemZiQ commented on task/02-numbers-tasks.js
> +  return Math.acos((x1 * x2 + y1 * y2) / (Math.sqrt(Math.pow(x1, 2) + Math.pow(y1, 2)) * Math.sqrt(Math.pow(x2, 2) + Math.pow(y2, 2)))); // eslint-disable-line
Пофиксил

2019-02-20 16:47 UTC, RemZiQ commented on task/02-numbers-tasks.js
> +  return +value.toString().split('').pop();
Пофиксил

2019-02-20 16:48 UTC, RemZiQ commented on task/02-numbers-tasks.js
> +  return Math.sqrt(a * a + b * b + c * c);
Пофиксил

2019-02-20 16:48 UTC, RemZiQ commented on task/03-date-tasks.js
> +  return (date.getFullYear() % 4 === 0) && (date.getFullYear() % 100 !== 0) || (date.getFullYear() % 400 === 0); // eslint-disable-line
Пофиксил

2019-02-20 16:49 UTC, RemZiQ commented on task/03-date-tasks.js
> +  let hours = +date.toISOString().substring(11, 13);
Пофиксил

2019-02-20 16:49 UTC, RemZiQ commented on task/04-arrays-tasks.js
> +  return arr.filter(elem => !!elem);
Пофиксил

2019-02-20 16:50 UTC, RemZiQ commented on task/04-arrays-tasks.js
>  function getMovingSum(arr) {
Переделал. Очень недооценил reduce

2019-02-20 16:50 UTC, RemZiQ commented on task/04-arrays-tasks.js
>  function propagateItemsByPositionIndex(arr) {
Переделал

2019-02-20 16:50 UTC, RemZiQ commented on task/04-arrays-tasks.js
> +  return arr.map(item => m.indexOf(item)).sort((a, b) => a - b).map(item => m[item]);  //eslint-disable-line
Переделал

2019-02-20 16:50 UTC, RemZiQ commented on task/04-arrays-tasks.js
> -  throw new Error('Not implemented');
Переделал

2019-02-20 16:53 UTC, RemZiQ commented on task/04-arrays-tasks.js
> +  return new Array(n).fill(0).map((item, indexMainArray) => {
Оставил как есть. Оставил коммент в скайпе.

2019-02-21 11:48 UTC, RamanRudski requested changes

2019-02-21 11:48 UTC, Erromanr commented on task/04-arrays-tasks.js
> +  arr.reduce((summ, current, index) => resultArray[index] = summ + current, 0); return resultArray; //eslint-disable-line
Можно сделать в одну строку,  используя только `reduce`,  без создания `resultArray `.

2019-02-22 07:59 UTC, RamanRudski approved these changes

2019-02-22 08:49 UTC, merged