Part 7
RemZiQ/js-assignments pull request #4
Opened 2019-03-05 15:22 UTC by RemZiQ

Added solutions for yield-tasks.

2019-03-20 13:49 UTC, RamanRudski requested changes

2019-03-20 13:49 UTC, RamanRudski commented on task/07-yield-tasks.js
>  }
каждый раз когда ты будешь вызывать  `fibonacciElement()` будет проходить новый цикл. Сделай решение таким образом , чтобы цикл создавался один, и на каждой итерации у тебя был `yield`.

2019-03-21 15:56 UTC, RemZiQ commented on task/07-yield-tasks.js
>  }
Пофиксил

2019-03-21 15:57 UTC, RamanRudski approved these changes

2019-03-22 08:43 UTC, merged